USE Bank;

CREATE TABLE Banks
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	BanksName NVARCHAR(30),
);


CREATE TABLE Cities
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	City NVARCHAR(30),
);


CREATE TABLE CityBank
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	BankId INT,
	CityId INT,
	FOREIGN KEY (BankId) REFERENCES Banks(Id) ON UPDATE CASCADE,
	FOREIGN KEY (CityId) REFERENCES Cities(Id) ON UPDATE CASCADE
);


CREATE TABLE SocStatus
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Stat NVARCHAR(30),
);

CREATE TABLE Clients
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	LastName NVARCHAR(30),
	FirstName NVARCHAR(30),
	Patronymic NVARCHAR(30),
	SocialStatId INT,
	FOREIGN KEY (SocialStatId) REFERENCES SocStatus(Id) ON UPDATE CASCADE
);


CREATE TABLE Cards 
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CardsName NVARCHAR(30),
);


CREATE TABLE CardBalance
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	BankId INT,
	ClientId INT,
	CardId INT,
	Balance DECIMAL,
	FOREIGN KEY (BankId) REFERENCES Banks(Id) ON UPDATE CASCADE,
	FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON UPDATE CASCADE,
	FOREIGN KEY (CardId) REFERENCES Cards(Id) ON UPDATE CASCADE
);


  CREATE TABLE ClientsBank
(
	ID INT IDENTITY(1,1) PRIMARY KEY,	
	ClientId INT,
	BankId INT,
	Balance DECIMAL,
	FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON UPDATE CASCADE,
	FOREIGN KEY (BankId) REFERENCES Banks (Id) ON UPDATE CASCADE
);

